name: test
on: [push, pull_request]
jobs:
  test-and-lint:
    name: Test and Lint on lowest supported Go version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: 'oldstable'
      - run: make test
  test:
    name: Test on highest supported Go version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: make ginkgo
