name: test
on: [push, pull_request]
jobs:
  test-and-lint:
    name: Test and Lint on go.mod version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: make test
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'stable', 'oldstable' ]
    name: Test on Go ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v4
      - run: make ginkgo
