name: test
on: [push, pull_request]
jobs:
  test-and-lint:
    name: Test and Lint Go 1.19
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
      - run: make test
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20' ]
    name: Test Go ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - run: make ginkgo
