name: test

on: [push, pull_request]

jobs:
  test-go-1-17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - uses: actions/checkout@v2
    - run: make ginkgo
  test-go-1-16:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: actions/checkout@v2
    - run: make test
  automerge:
    needs: test-go-1-16
    runs-on: ubuntu-latest
    if: ${{ success() && github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
    steps:
    - uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_numner: context.issue.number,
            merge_method: 'squash'
          })
